lang-api/config/routes.rb
Rails.application.routes.draw do
  resources :languages

  resources :articles do
    collection do
      get :extract
    end
  end

  resources :tasks do
    resources :items
  end

  resources :words do
    resources :sentences
  end

  resources :task_articles
  
  # standard devise routes available at /users
  # NOTE: make sure this comes first!!!
  devise_for :users

  # token auth routes available at /api/v1/auth
  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

lang-api/app/models/word.rb
class Word < ApplicationRecord
  include Filterable
  include PgSearch

  belongs_to :language

  has_many :task_words
  has_many :tasks, through: :task_words

  has_many :user_words
  has_many :users, through: :user_words

  has_many :word_sentences
  has_many :sentences, through: :word_sentences

  has_many :article_words
  has_many :articles, through: :article_words

  # Filter scopes
  pg_search_scope :text, :against     => :text
  pg_search_scope :alt_text, :against => :alt_text
  pg_search_scope :pinyin, :against   => :pinyin
  pg_search_scope :meaning, :against  => :meaning
  pg_search_scope :note, :against     => :note
  scope :task_id,   -> (task_id) { joins(:task_words).where("task_id = ?", task_id) }
  scope :article_id,-> (article_id) { joins(:article_words).where("article_id = ?", article_id) }
end

lang-api/app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]
  before_action :set_task, only: [:create, :update, :destroy]
  before_action :set_article, only: [:create, :update, :destroy]
  respond_to :html, :json
  
  # GET /words
  # GET /words.json
  def index
    @words = current_user.words.filter(filter_params).order('updated_at ASC')
    respond_with(@words)
  end

  # GET /words/1
  # GET /words/1.json
  def show
    respond_to do |format|
      format.json  { render :json => @word.to_json(:include => [:sentences])}
    end
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = current_user.words.new(word_params)
    if @word.save
      @user_word = @word.user_words.new(user_id: current_user.id, is_owner: true)

      if @task then @task.words << @word end
      if @article then @article.words << @word end
    end

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    def set_task
      @task = params[:task_id]? Task.find(params[:task_id]) : nil
    end

    def set_article
      @article = params[:article_id]? Article.find(params[:article_id]) : nil
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:text, :alt_text, :pinyin, :meaning, :note, :language_id)
    end

    def filter_params
      params.permit(:text, :alt_text, :pinyin, :meaning, :note, :task_id, :article_id)
    end
end

lang-api/app/helpers/words_helper.rb
module WordsHelper
end

lang-api/app/views/words/_form.html.erb
<%= form_for(word) do |f| %>
  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="field">
    <%= f.label :alt_text %>
    <%= f.text_field :alt_text %>
  </div>

  <div class="field">
    <%= f.label :pinyin %>
    <%= f.text_field :pinyin %>
  </div>

  <div class="field">
    <%= f.label :meaning %>
    <%= f.text_area :meaning %>
  </div>

  <div class="field">
    <%= f.label :note %>
    <%= f.text_area :note %>
  </div>

  <div class="field">
    <%= f.label :language_id %>
    <%= f.text_field :language_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lang-api/app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

lang-api/app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Words</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Alt Text</th>
      <th>Pinyin</th>
      <th>Meaning</th>
      <th>Note</th>
      <th>Language</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.text %></td>
        <td><%= word.alt_text %></td>
        <td><%= word.pinyin %></td>
        <td><%= word.meaning %></td>
        <td><%= word.note %></td>
        <td><%= word.language %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>

lang-api/app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Back', words_path %>

lang-api/app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @word.text %>
</p>

<p>
  <strong>Pinyin:</strong>
  <%= @word.pinyin %>
</p>

<p>
  <strong>Meaning:</strong>
  <%= @word.meaning %>
</p>

<p>
  <strong>Note:</strong>
  <%= @word.note %>
</p>

<p>
  <strong>Language:</strong>
  <%= @word.language %>
</p>

<p>
  <strong>User:</strong>
  <%= @word.user %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>